SH2="$( dirname ${0} )/sh2"	# candidate sh2
test -d "${SH2}" || exit 2	# missing sh2
. ${SH2}/error.sh		# error handling
error "true"			# show errors
. ${SH2}/cecho.sh		# colored echo
. ${SH2}/cache.sh		# cache
. ${SH2}/aliases/commands.sh 	# commands
geo-ip-lookup-payload() {
  cecho green "looking up ip geolocation ..."
  curl --silent "http://api.db-ip.com/v2/free/${candidate_ip}"
  cecho green "done looking up ip geolocation"
}
geo-ip-lookup() { { local candidate_ip ; candidate_ip="${1}" ; }
  {
    cache \
    ${cache}/${FUNCNAME}-${candidate_ip} \
    ${FUNCNAME}-payload
  }
}
geo-ip() {
  commands
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
geo-ip ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 09 Jul 2019 09:27:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
